### ISSUE TITLE
Dimensional Manager - Config

### ISSUE THREAD

**Issue by Kagenokami** [GTNewHorizons/ThaumicHorizons#80]
### Mod Version

1.6.5

### Bug Report

Despite the latest updates moving to ensure that the mod listens to it's config, I've noticed an error with the dimensional manager. When setting the dimension to another value, it will successfully register the dimension to that value on the first load of the world; however, subsequent attempts to open that world results in a crash. Using Anti ID Conflict, it shows that the dimension's id changes, but the provider id does not change to match.

I'd be fine leaving it as the original to make it work, but I have the planetary mod that prefers that no dimensions are registered after to, due to how it processes planet (dimension) creation. Plus, I like to keep my IDs to a minimum to avoid the need for extension mods.

AntiIDConflict: 

-14 : Pocket Plane, Provider: (id: 69, class: class com.kentington.thaumichorizons.common.lib.WorldProviderPocketPlane)

Crash: 

[07:43:03] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getSimpleName()" because the return value of "java.util.Hashtable.get(Object)" is null
	at Launch//net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302) ~[DimensionManager.class:?]
	at Launch//net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160) ~[aqo.class:?]
	at Launch//net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at Launch//net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14) ~[mm.class:?]
	at Launch//net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65) ~[bsx.class:?]
	at Launch//net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) ~[bsx.class:?]
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

### Java Version

Java 21

### Mod List or GTNH Pack Version

1.7.10
AE2 Fluid Crafting
AE2 Stuff
AE2 Wireless Crafting Terminal
AE2-Additions
Advanced Chimneys
Advanced Rocketry
Advanced Solar Panels
AdvancedVanilla2
Aether Aspects
Aether II
AgriCraft
Alchemical Grate
AnimationAPI
Another One Bites The Dust
Another One Bites The Dust: Ore Chunks
Another One Bites The Dust: Singularities
Anti Id Conflict
Antique Atlas
Antique Atlas Overlay
AppleCore
Applied Energistics 2
Applied Exchange
ArchitectureCraft
Aroma1997's Dimensional World
Aroma1997Core
Aroma1997DimensionFix
Ars Magica 2
Automagy
Automated Redstone
Avaritia
BD lib
BRCore
Baubles-Hud
BeeBetterAtBees
Better Placement
Better Sleeping
BetterBuildersWands
BiblioCraft
BiblioWoods Biomes O'Plenty Edition
BiblioWoods Forestry Edition
BiblioWoods Natura Edition
Big Reactors
Binnie Core
Biomes O' Plenty
Blood Magic: Alchemical Wizardry
Botania
Botania-Energistics
BotaniaVisualizer
BuildCraft
BuildCraft Compat
CCTweaks
CD4017BE_lib
Campfire Backport
Carbon Config Library
Carpenter's Blocks
Catwalks Mod
CazzarCoreLib
Chisel
Chisel Facades
CoFH Core
CodeChicken Core
CodeChickenLib Unofficial 1.7.10
Compact Machines
Computer LandMark
ComputerCraft
Controlling
Cookie Core
CoreTweaks
CosmeticArmorReworked
Craft Arcanum
Crafting EX
Crafting Tweaks
CraftingSlabs
CreativeCore
Decocraft
Dense Ores
Description Tags
Dimensional Doors
Dimensional Pockets
Directional Redstone
Dumb Library
DummyCore
Dynamic Dynamos
EIORecipesTEInductionSmelter
EXCore
EasyBreeding
Electro-Magic Tools
Enchanting Plus
Enchiridion 2
Ender IO
Ender Zoo
EnderCore
EnderStorage
EnderTanks
EnderTech
EnhancedPortals
EnviroMine
Essentia Pipes
Et Futurum Golems Addon
Et Futurum Requiem
Ex Astris
Ex Fusile
Ex Nihilo
ExpandedBonemeal
Extra Cells
Extra Crafting Storage
Extra Golems
Extra Golems Waila Addon
Extra Utilities
Extra Utilities Tweaks
ExtraTiC
Fast Leaf Decay
Fire Peripherals
FloatingItems
Food Details
Forbidden Magic
Forestry
Forestry Fermenter Addon
Forge Endertech
Funky Locomotion
GTNH Lib
Gadomancy
Gendustry
Gilded Games Utility
Graviation Suite
Guide-API
Horizontal Backport
Iguana Tinker Tweaks
Immersive Engineering
Immersive Engineering Blueprint Tweaker
Immersive Integration
Industrial Expansion
Industrial Peripheral
IndustrialCraft 2
Infini-TiC
InfusinBrewing
Inventory Tweaks
Iron Chest Minecarts
Iron Chests
Iron Tanks
JABBA
JAOPCA
JAOPCASingularities
Jukebox Reloaded
LLibrary
Looking Glass
MJUtils
Magic Bees
Magical Decorations
Malisis' Doors
Mantle
McJtyLib
Metal Golems Addon
MineFactory Reloaded
MineTweaker 3
Minecraft Comes Alive
MmmMmmMmmMmm
ModularUI
Morpheus
Mounted Pearl
Mouse Tweaks
NEI Addons
NEI Addons
NEI Utilities
NEIIntegration
Natura
Nether Ores
Nether Portal Fix
NetheritePlus+
Netherlicious
NodalMechanics
NotEnoughEnergistics
NotEnoughIDs
NotEnoughItems
Nuclear Control 2
NuclearCraft
OC Glasses
OC-Minecarts
OCSLua
ObsidiPlates
OnlinePictureFrame
OpenBlocks
OpenComputers
OpenFM
OpenLights
OpenMods
OpenPeripheralAddons
OpenPeripheralCore
OpenPeripheralIntegration
OpenPrinter
OpenSecurity
OpenSecurity
OpenSensors
Origin
Pam's Clayspawn
Pam's DesertCraft
Pam's Get all the Seeds!
Pam's Harvest the Nether
Pam's HarvestCraft
Pam's Need Moar Sticks
Pam's Simple Recipes
Pam's Weee! Flowers
Platforms
Potion Packs
RF Utilities
RFDrills
RFTools
RadixCore
Redstone Arsenal
Redstone Paste
Regrowable Leaves
Ritual Enchanting
Runic Dungeons
Sanguimancy
Sanguine Utilities
SeedDrop
ShetiPhian-Core
Simply Paths
Slabify
Sleeping Bag
Small Stairs (unofficial)
Soulbound Enchantment
Spatial IO Compat
Steve's Addons
Steve's Carts 2
Steve's Factory Manager
Steve's Workshop
Storage Drawers
TC Inventory Scanning
TC Node Tracker
TC Research-Helper
TC4 Tweak
TCBotaniaExoflame
Tainted Magic
ThaumOres
ThaumPatch
Thaumaturgical Knowledge
Thaumcraft
Thaumcraft Integration
Thaumcraft Mob Aspects
Thaumcraft NEI Additions
Thaumcraft NEI Plugin
Thaumic Alchemy
Thaumic Bases
Thaumic Concilium
Thaumic Dyes
Thaumic Energistics
Thaumic Errata
Thaumic Exploration
Thaumic Insurgence
Thaumic Tinkerer
Thaumic Utilities
ThaumicHorizons
ThaumicMixins
The SecretRoomsMod
The Spice of Life - Carrot Edition
The Twilight Forest
Thermal Casting
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Thermal Recycling
Thermal Shade
Thermal Singularities
Thermal Smeltery Redux
Thermal Tinkering
TiC Tooltips
TileEntity Reset Fix
Tinker I/O
Tinkers Construct Auto Tool Station
Tinkers Mechworks
Tinkers' Construct
Tinkers' Golems Addon
Tinkers' Modifiers
Tinkers' Steelworks
Tinkers' in the Sky
Translocator
Traveller's Gear
Treecapitator
Twilight Forest Portal Catalyst
UniMixins
WAILA Plugins
WAILA-features
Waila
Waila Harvestability
WailaAddonBC
WanionLib
WarpTheory
WatkinsBase
What Are We Looking At
Witchery
Witchery++
WoodStuff
Ztones-Unofficial
carpentersblocks
ic2
jaad-0.8.5
libVulpes
lwjgl3ify
mp3spi-1.9.5-1
p455w0rd's Library
vorbisspi-1.0.3-1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by chochem** [comment]
> Despite the latest updates moving to ensure that the mod listens to it's config

that was just about one particular config, sorry for the confusion.

**Comment by Kagenokami** [comment]
> > Despite the latest updates moving to ensure that the mod listens to it's config
> 
> that was just about one particular config, sorry for the confusion.

Ah, that'd explain things. It also, admittedly, took me an EMBARRASSINGLY long time to figure out what was breaking my game when Horizons was loaded. Been trying to figure it out over the past couple releases. The mention of config changes not being checked by the mod gave me that "Ah-HA!" moment that let me track it down.
